#  Copyright Copyright (C) 2001-2021 Force Dimension, Switzerland.
#  All Rights Reserved.
#
#  Force Dimension SDK 3.11.1


# Eigen  dependency
EIGEN     = $(TOP_DIR)/externals/Eigen
CXXFLAGS += -I$(EIGEN)
